### ISSUE TITLE
data/PDBBind_processed not found

### ISSUE THREAD

**Issue by ydzdfci** [shuyana/DiffusionProteinLigand#2]
in preprocess_pdbbind.py, line 18,19
    if input_dir.is_dir():
        raise ValueError(f"The PDBbind dataset not found: {input_dir}.")
I doubt if this is right. If I put unziped folder PDBBind_processed under data/, the path will be data/PDBBind_processed, which is a directory, I think it is 
if not input_dir.is_dir():

**Comment by shuyana** [comment]
Dear Yingde,

Thank you for your interest in our model and for bringing this issue to our attention. As you pointed out, this is a bug, and I have fixed it.

Thank you again for your valuable feedback. I will close the issue as resolved, but please feel free to reopen it if you encounter any further issues.

Best regards,
Shuya Nakata.
