### ISSUE TITLE
tmalign error

### ISSUE THREAD

**Issue by ydzdfci** [shuyana/DiffusionProteinLigand#4]
when running generate example 
```
python generate.py \
    --ckpt_path "checkpoints/DPL_v1.ckpt" \
    --output_dir "workdir/generate/example_DPL" \
    --protein "LSEQLKHCNGILKELLSKKHAAYAWPFYKPVDASALGLHDYHDIIKHPMDLSTVKRKMENRDYRDAQEFAADVRLMFSNCYKYNPPDHDVVAMARKLQDVFEFRYAKMPD" \
    --ligand "Cc1ccc2c(c1c3cc(cc4c3nc([nH]4)C5CC5)c6c(noc6C)C)cccn2" \
    --num_samples 8
```
Predicting DataLoader 0: 100%
Traceback (most recent call last):
  File "/DiffusionProteinLigand/generate.py", line 170, in <module>
    main(args)
  File "/DiffusionProteinLigand/generate.py", line 132, in main
    run_tmalign(sample_protein, ref_protein),
  File "/DiffusionProteinLigand/dpl/tmalign.py", line 31, in run_tmalign
    tmscore = float(line.split()[3])  # TM2
IndexError: list index out of range
Traceback (most recent call last):
  File "DiffusionProteinLigand/generate.py", line 170, in <module>
    main(args)
  File "DiffusionProteinLigand/generate.py", line 132, in main
    run_tmalign(sample_protein, ref_protein),
  File "DiffusionProteinLigand/dpl/tmalign.py", line 31, in run_tmalign
    tmscore = float(line.split()[3])  # TM2
IndexError: list index out of range

created environment from environment.yml
changed torchmetrics to 0.11.4 to avoid RuntimeError: cannot import name '_compare_version' from 'torchmetrics.utilities.imports
added line as suggested in [weakref issue](https://github.com/shuyana/DiffusionProteinLigand/issues/3)
```
trainer = pl.Trainer.from_argparse_args(
    args,
    accelerator="auto",
    strategy="ddp",  # <- Added: specify the trainer strategy explicitly
    default_root_dir=args.output_dir,
    max_epochs=-1,
)
```

**Comment by ydzdfci** [comment]
Figured out
Since TMalign changed [output format](https://seq2fun.dcmb.med.umich.edu//TM-align/example/873772.html). I modified dpl.tmalign.py
```
lines = output.splitlines()
lines = [x for x in lines if x.startswith('TM-score')]
line = lines[-1]  # <- I don't know if this is correct, as second chain is ref.pdb in cmd = ["TMalign", prb_path, ref_path]
tmscore = float(line.split()[1])  # TM2   # <- TM-score= 0.85377 (if normalized by length of Chain_2)
```

**Comment by shuyana** [comment]
Dear ydzdfci,

Thank you for reporting another issue. I appreciate your efforts to resolve the issue and share the relevant information!

As you pointed out, the error you encountered seems to be related to the output format of TMalign. However, I have not been able to reproduce it. The version of TMalign I am using is `Version 20220412`.

I have created my environment from [the fixed version of environment.yml](https://github.com/shuyana/DiffusionProteinLigand/commit/bc9461efaf67a1ffa5b6b98dfaffa86aa9a18670) and added the line suggested in the weakref issue.

Could you please tell me the version of TMalign you are using?

Best,
Shuya Nakata

**Comment by shuyana** [comment]
P.S.
Your solution should work with [the normal output format of TMalign](https://seq2fun.dcmb.med.umich.edu//TM-align/example/873772.html), but since the `-outfmt 2` option is specified in [dpl/tmalign.py](https://github.com/shuyana/DiffusionProteinLigand/blob/bc9461efaf67a1ffa5b6b98dfaffa86aa9a18670/dpl/tmalign.py#L21), the output of TMalign should be in the following format:

```
#PDBchain1      PDBchain2       TM1     TM2     RMSD    ID1     ID2     IDali   L1      L2      Lali
prb.pdb        ref.pdb        0.9851  0.9941  0.30    0.991   1.000   1.000   110     109     109
Total CPU time is  0.01 seconds
```

**Comment by ydzdfci** [comment]
I see. I think the default version on my workstation is 20160521, which is old that not support -outfmt.
Thanks
