### ISSUE TITLE
torchmetrics error

### ISSUE THREAD

**Issue by ydzdfci** [shuyana/DiffusionProteinLigand#5]
if installed directly from environment.yml provided, please run
`pip install torchmetrics==0.11.4`
changed torchmetrics to 0.11.4 to avoid RuntimeError: cannot import name '_compare_version' from 'torchmetrics.utilities.imports

**Comment by shuyana** [comment]
Dear ydzdfci,

Thank you very much for reporting the issue and suggesting a solution (sorry for the late reply)! I was able to reproduce the error and confirmed that adding `torchmetrics==0.11.4` to the environment.yml file resolves the issue. I have pushed the fix, so please check it out!

I have closed the issue as resolved, but please feel free to reopen it if you encounter any further issues.

Best regards,
Shuya Nakata
